manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: urob
      revision: main-3.2  # Zephyr 3.2 branch this keymap targets (matches the zmk-build-arm:3.2 image in build.yml)
      import: app/west.yml
  self:
    path: config
